#!/usr/bin/env python3
"""
Phase 2 MVP: local metadata review/edit UI for setup-image output.

Loads SETUP-REVIEW.json, serves a local web page, and writes updated GAME.TXT
metadata back into each game folder.

Examples:
  python tools/metadata-ui.py --launcher-dir /mnt/dos/DGB
  python tools/metadata-ui.py --review-file /mnt/dos/DGB/SETUP-REVIEW.json --port 8765
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import threading
import webbrowser
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

FIELDS = ["title", "year", "genre", "publisher", "exe", "setup", "note"]
YEAR_MIN = 1980
YEAR_MAX = 2099


@dataclass
class Record:
    dir: str
    exe: str
    title: str
    year: str
    genre: str
    publisher: str
    note: str
    needs_review: bool
    candidates: list[str]


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Local metadata editor for SETUP-REVIEW.json")
    ap.add_argument(
        "--launcher-dir",
        type=Path,
        help="Launcher directory containing SETUP-REVIEW.json",
    )
    ap.add_argument(
        "--review-file",
        type=Path,
        help="Explicit SETUP-REVIEW.json path (overrides --launcher-dir)",
    )
    ap.add_argument("--host", default="127.0.0.1", help="Bind host (default: 127.0.0.1)")
    ap.add_argument("--port", type=int, default=8765, help="Bind port (default: 8765)")
    ap.add_argument("--no-browser", action="store_true", help="Do not auto-open browser")
    return ap.parse_args()


def normalize_text(value: Any, maxlen: int | None = None) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").strip()
    if maxlen is not None:
        text = text[:maxlen]
    return text


def normalize_year(value: Any) -> str:
    year = normalize_text(value, maxlen=4)
    if year == "":
        return ""
    if not year.isdigit():
        raise ValueError("year must be numeric")
    y = int(year)
    if y < YEAR_MIN or y > YEAR_MAX:
        raise ValueError(f"year must be between {YEAR_MIN} and {YEAR_MAX}")
    return year


def load_review(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"review file not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if "records" not in data or not isinstance(data["records"], list):
        raise ValueError("invalid review file: missing records array")
    return data


def write_game_txt(game_dir: Path, record: dict[str, Any]) -> None:
    meta: dict[str, str] = {
        "title": normalize_text(record.get("title"), 80),
        "year": normalize_year(record.get("year")),
        "genre": normalize_text(record.get("genre"), 40),
        "publisher": normalize_text(record.get("publisher"), 80),
        "exe": normalize_text(record.get("exe"), 64),
        "setup": normalize_text(record.get("setup"), 64),
        "note": normalize_text(record.get("note"), 120),
    }

    lines = ["# DOS Game Browser metadata - edited by tools/metadata-ui.py", ""]
    for key in FIELDS:
        if meta[key] != "":
            lines.append(f"{key}={meta[key]}")
    text = "\n".join(lines) + "\n"
    (game_dir / "GAME.TXT").write_text(text, encoding="utf-8")


def compute_needs_review(record: dict[str, Any]) -> bool:
    return any(normalize_text(record.get(k)) == "" for k in ("title", "year", "publisher"))


class MetadataApp:
    def __init__(self, review_file: Path):
        self.review_file = review_file
        self.lock = threading.Lock()
        self.payload = load_review(review_file)
        self.records = self.payload["records"]
        self.launcher_dir = self._resolve_launcher_dir()
        self.scan_root = self._resolve_scan_root()

    def _resolve_launcher_dir(self) -> Path:
        launcher = self.payload.get("launcher_dir")
        if launcher:
            p = Path(str(launcher)).resolve()
            if p.is_dir():
                return p
        return self.review_file.parent.resolve()

    def _resolve_scan_root(self) -> Path:
        scan_root = self.payload.get("scan_root")
        if scan_root:
            p = Path(str(scan_root)).resolve()
            if p.is_dir():
                return p

        guessed = (self.launcher_dir / "GAMES").resolve()
        if guessed.is_dir():
            return guessed

        dirs: list[Path] = []
        for rec in self.records:
            d = rec.get("dir")
            if d:
                dirs.append(Path(str(d)).resolve().parent)
        if dirs:
            return Path(os.path.commonpath([str(d) for d in dirs])).resolve()

        raise ValueError("cannot infer scan root; provide review generated by setup-image.py")

    def save_review(self) -> None:
        self.review_file.write_text(json.dumps(self.payload, indent=2), encoding="utf-8")

    def state(self) -> dict[str, Any]:
        with self.lock:
            total = len(self.records)
            unresolved = sum(1 for r in self.records if r.get("needs_review", False))
            return {
                "reviewFile": str(self.review_file),
                "scanRoot": str(self.scan_root),
                "launcherDir": str(self.launcher_dir),
                "total": total,
                "unresolved": unresolved,
                "records": self.records,
            }

    def regenerate_index(self) -> dict[str, Any]:
        out_lst = self.launcher_dir / "GAMES.LST"
        cmd = [
            sys.executable,
            str(Path(__file__).resolve().parents[1] / "tools" / "scan-games.py"),
            "--games",
            str(self.scan_root),
            "--out",
            str(out_lst),
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            detail = (proc.stderr or proc.stdout).strip()
            raise RuntimeError(detail or "scan-games.py failed")
        return {
            "output": str(out_lst),
            "stdout": (proc.stdout or "").strip(),
        }

    def _build_updates(self, rec: dict[str, Any], patch: dict[str, Any]) -> dict[str, str]:
        return {
            "title": normalize_text(patch.get("title", rec.get("title", "")), 80),
            "year": normalize_year(patch.get("year", rec.get("year", ""))),
            "genre": normalize_text(patch.get("genre", rec.get("genre", "")), 40),
            "publisher": normalize_text(patch.get("publisher", rec.get("publisher", "")), 80),
            "exe": normalize_text(patch.get("exe", rec.get("exe", "")), 64),
            "setup": normalize_text(patch.get("setup", rec.get("setup", "")), 64),
            "note": normalize_text(patch.get("note", rec.get("note", "")), 120),
        }

    def update_record(self, idx: int, patch: dict[str, Any]) -> dict[str, Any]:
        with self.lock:
            if idx < 0 or idx >= len(self.records):
                raise IndexError("record index out of range")
            rec = self.records[idx]
            game_dir = Path(rec["dir"])
            if not game_dir.is_dir():
                raise FileNotFoundError(f"game directory not found: {game_dir}")

            updates = self._build_updates(rec, patch)

            rec.update(updates)
            rec["needs_review"] = compute_needs_review(rec)
            write_game_txt(game_dir, rec)
            self.save_review()
            return rec

    def bulk_update(self, ids: list[int], patch: dict[str, Any]) -> dict[str, Any]:
        with self.lock:
            if not ids:
                raise ValueError("ids cannot be empty")

            clean_ids: list[int] = []
            for raw in ids:
                idx = int(raw)
                if idx < 0 or idx >= len(self.records):
                    raise IndexError(f"record index out of range: {idx}")
                clean_ids.append(idx)

            unique_ids = sorted(set(clean_ids))
            updated: list[int] = []
            for idx in unique_ids:
                rec = self.records[idx]
                game_dir = Path(rec["dir"])
                if not game_dir.is_dir():
                    raise FileNotFoundError(f"game directory not found: {game_dir}")

                updates = self._build_updates(rec, patch)
                rec.update(updates)
                rec["needs_review"] = compute_needs_review(rec)
                write_game_txt(game_dir, rec)
                updated.append(idx)

            self.save_review()
            return {"updated": updated, "count": len(updated)}


def make_handler(app: MetadataApp):
    class Handler(BaseHTTPRequestHandler):
        def _json(self, status: int, payload: dict[str, Any]) -> None:
            raw = json.dumps(payload).encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)

        def _html(self, html: str) -> None:
            raw = html.encode("utf-8")
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)

        def log_message(self, fmt: str, *args: Any) -> None:
            return

        def do_GET(self) -> None:
            if self.path in ("/", "/index.html"):
                self._html(INDEX_HTML)
                return
            if self.path == "/api/state":
                self._json(HTTPStatus.OK, app.state())
                return
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})

        def do_POST(self) -> None:
          if self.path == "/api/regenerate":
            try:
              result = app.regenerate_index()
              self._json(HTTPStatus.OK, {"ok": True, **result})
            except (RuntimeError, ValueError) as exc:
              self._json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            return

          if self.path == "/api/bulk-update":
            length = int(self.headers.get("Content-Length", "0"))
            raw = self.rfile.read(length)
            try:
              payload = json.loads(raw.decode("utf-8")) if raw else {}
            except json.JSONDecodeError:
              self._json(HTTPStatus.BAD_REQUEST, {"error": "invalid json"})
              return

            ids = payload.get("ids")
            patch = payload.get("patch", {})
            if not isinstance(ids, list):
              self._json(HTTPStatus.BAD_REQUEST, {"error": "ids must be an array"})
              return
            if not isinstance(patch, dict):
              self._json(HTTPStatus.BAD_REQUEST, {"error": "patch must be an object"})
              return

            try:
              result = app.bulk_update(ids, patch)
              self._json(HTTPStatus.OK, {"ok": True, **result})
            except IndexError as exc:
              self._json(HTTPStatus.NOT_FOUND, {"error": str(exc)})
            except (ValueError, FileNotFoundError) as exc:
              self._json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            except Exception as exc:
              self._json(HTTPStatus.INTERNAL_SERVER_ERROR, {"error": f"internal error: {exc}"})
            return

          if not self.path.startswith("/api/record/"):
            self._json(HTTPStatus.NOT_FOUND, {"error": "not found"})
            return

          try:
            idx_str = self.path.rsplit("/", 1)[1]
            idx = int(idx_str)
          except Exception:
            self._json(HTTPStatus.BAD_REQUEST, {"error": "invalid record id"})
            return

          length = int(self.headers.get("Content-Length", "0"))
          raw = self.rfile.read(length)
          try:
            patch = json.loads(raw.decode("utf-8")) if raw else {}
          except json.JSONDecodeError:
            self._json(HTTPStatus.BAD_REQUEST, {"error": "invalid json"})
            return

          try:
            rec = app.update_record(idx, patch)
            self._json(HTTPStatus.OK, {"ok": True, "record": rec})
          except IndexError as exc:
            self._json(HTTPStatus.NOT_FOUND, {"error": str(exc)})
          except (ValueError, FileNotFoundError) as exc:
            self._json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
          except Exception as exc:
            self._json(HTTPStatus.INTERNAL_SERVER_ERROR, {"error": f"internal error: {exc}"})

    return Handler


INDEX_HTML = """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>DGB Metadata Editor</title>
  <style>
    :root {
      --paper: #f3efe2;
      --ink: #1e2a39;
      --accent: #0f766e;
      --accent-2: #b45309;
      --line: #d7cfbb;
      --danger: #9f1239;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      color: var(--ink);
      background:
        radial-gradient(circle at 15% 15%, #f9f4df 0 140px, transparent 150px),
        radial-gradient(circle at 85% 75%, #e6f2f1 0 180px, transparent 190px),
        linear-gradient(180deg, #f6f2e8, #eee8d7);
      font-family: Georgia, "Times New Roman", serif;
      min-height: 100vh;
    }
    .wrap {
      max-width: 1100px;
      margin: 0 auto;
      padding: 20px;
    }
    .hero {
      border: 2px solid var(--line);
      background: rgba(255,255,255,0.7);
      border-radius: 12px;
      padding: 16px;
      box-shadow: 0 8px 24px rgba(30,42,57,0.08);
    }
    h1 {
      margin: 0 0 6px;
      font-size: 30px;
      letter-spacing: 0.5px;
    }
    .sub {
      margin: 0;
      font-size: 14px;
    }
    .summary {
      margin-top: 12px;
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
    }
    .pill {
      padding: 6px 10px;
      border: 1px solid var(--line);
      background: #fffdf6;
      border-radius: 999px;
      font-size: 13px;
    }
    .grid {
      margin-top: 14px;
      display: grid;
      grid-template-columns: 340px 1fr;
      gap: 14px;
    }
    .panel {
      border: 2px solid var(--line);
      background: rgba(255,255,255,0.85);
      border-radius: 12px;
      overflow: hidden;
    }
    .panel h2 {
      margin: 0;
      padding: 10px 12px;
      border-bottom: 1px solid var(--line);
      font-size: 16px;
      background: #fff9e8;
    }
    .toolbar {
      display: flex;
      gap: 8px;
      padding: 8px 10px;
      border-bottom: 1px solid var(--line);
    }
    .toolbar input {
      flex: 1;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 8px;
      font-size: 14px;
      font-family: "Courier New", monospace;
      background: #fff;
    }
    .toolbar label {
      font-size: 13px;
      white-space: nowrap;
      display: flex;
      align-items: center;
      gap: 4px;
    }
    .list {
      max-height: 65vh;
      overflow: auto;
    }
    .item {
      border-bottom: 1px dashed var(--line);
      padding: 10px;
      cursor: pointer;
      animation: fadeIn 0.2s ease;
    }
    .item:hover { background: #fffbed; }
    .item.active { background: #ebf6f5; border-left: 4px solid var(--accent); }
    .item .t { font-weight: bold; font-size: 14px; }
    .item .d { font-size: 12px; opacity: 0.8; font-family: "Courier New", monospace; }
    .item .f { font-size: 11px; margin-top: 4px; }
    .badge {
      color: #fff;
      background: var(--danger);
      border-radius: 6px;
      padding: 2px 6px;
      font-size: 10px;
      margin-left: 6px;
    }
    form {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px;
      padding: 12px;
    }
    .full { grid-column: 1 / -1; }
    label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
    input, textarea {
      width: 100%;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 8px;
      background: #fff;
      font-size: 14px;
      font-family: Georgia, "Times New Roman", serif;
    }
    textarea { min-height: 80px; resize: vertical; }
    .actions {
      grid-column: 1 / -1;
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap: 10px;
    }
    button {
      border: 0;
      border-radius: 8px;
      padding: 10px 14px;
      cursor: pointer;
      font-weight: bold;
      color: #fff;
      background: linear-gradient(135deg, var(--accent), #115e59);
    }
    button:hover { filter: brightness(1.05); }
    .status {
      font-size: 13px;
      color: var(--accent-2);
      min-height: 18px;
    }
    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(2px); }
      to { opacity: 1; transform: translateY(0); }
    }
    @media (max-width: 900px) {
      .grid { grid-template-columns: 1fr; }
      form { grid-template-columns: 1fr; }
    }
  </style>
</head>
<body>
  <div class=\"wrap\">
    <section class=\"hero\">
      <h1>DGB Metadata Editor</h1>
      <p class=\"sub\">Phase 2 MVP: edit game metadata from setup review, write GAME.TXT, and clear unresolved entries.</p>
      <div class=\"summary\">
        <span class=\"pill\" id=\"sum-file\">review: -</span>
        <span class=\"pill\" id=\"sum-total\">total: 0</span>
        <span class=\"pill\" id=\"sum-unresolved\">needs review: 0</span>
      </div>
    </section>

    <div class=\"grid\">
      <section class=\"panel\">
        <h2>Records</h2>
        <div class=\"toolbar\">
          <input id=\"search\" placeholder=\"search title / exe / dir\" />
          <label><input type=\"checkbox\" id=\"only-unresolved\" /> unresolved</label>
        </div>
        <div id=\"list\" class=\"list\"></div>
      </section>

      <section class=\"panel\">
        <h2>Editor</h2>
        <form id=\"editor\">
          <div class=\"full\"><label>Directory</label><input id=\"dir\" readonly /></div>
          <div><label>Title</label><input id=\"title\" required /></div>
          <div><label>Year</label><input id=\"year\" placeholder=\"1992\" inputmode=\"numeric\" maxlength=\"4\" /></div>
          <div><label>Genre</label><input id=\"genre\" /></div>
          <div><label>Publisher</label><input id=\"publisher\" /></div>
          <div><label>Executable</label><input id=\"exe\" required /></div>
          <div><label>Setup</label><input id=\"setup\" /></div>
          <div class=\"full\"><label>Note</label><textarea id=\"note\"></textarea></div>
          <div class=\"full\"><label>Candidates</label><input id=\"candidates\" readonly /></div>
          <div class=\"actions\">
            <button type=\"button\" id=\"prev\">Prev</button>
            <button type=\"button\" id=\"next\">Next</button>
            <button type=\"button\" id=\"next-unresolved\">Next Unresolved</button>
            <button type=\"submit\">Save GAME.TXT + review state</button>
            <button type=\"button\" id=\"regen\">Regenerate GAMES.LST</button>
            <span class=\"status\" id=\"status\"></span>
          </div>
          <div class=\"full\" style=\"margin-top: 6px; border-top: 1px dashed var(--line); padding-top: 10px;\">
            <label>Bulk Apply to Filtered Unresolved</label>
            <div style=\"display: grid; grid-template-columns: 1fr 1fr 1fr auto; gap: 8px; margin-top: 6px;\">
              <input id=\"bulk-year\" placeholder=\"year\" inputmode=\"numeric\" maxlength=\"4\" />
              <input id=\"bulk-publisher\" placeholder=\"publisher\" />
              <input id=\"bulk-genre\" placeholder=\"genre\" />
              <button type=\"button\" id=\"bulk-apply\">Apply</button>
            </div>
          </div>
        </form>
      </section>
    </div>
  </div>

  <script>
    const state = {
      records: [],
      filtered: [],
      selected: -1,
    };

    const els = {
      list: document.getElementById('list'),
      search: document.getElementById('search'),
      onlyUnresolved: document.getElementById('only-unresolved'),
      status: document.getElementById('status'),
      sumFile: document.getElementById('sum-file'),
      sumTotal: document.getElementById('sum-total'),
      sumUnresolved: document.getElementById('sum-unresolved'),
      dir: document.getElementById('dir'),
      title: document.getElementById('title'),
      year: document.getElementById('year'),
      genre: document.getElementById('genre'),
      publisher: document.getElementById('publisher'),
      exe: document.getElementById('exe'),
      setup: document.getElementById('setup'),
      note: document.getElementById('note'),
      candidates: document.getElementById('candidates'),
      form: document.getElementById('editor'),
      regen: document.getElementById('regen'),
      prev: document.getElementById('prev'),
      next: document.getElementById('next'),
      nextUnresolved: document.getElementById('next-unresolved'),
      bulkYear: document.getElementById('bulk-year'),
      bulkPublisher: document.getElementById('bulk-publisher'),
      bulkGenre: document.getElementById('bulk-genre'),
      bulkApply: document.getElementById('bulk-apply'),
    };

    function setStatus(msg, isError=false) {
      els.status.textContent = msg;
      els.status.style.color = isError ? '#9f1239' : '#0f766e';
    }

    async function loadState() {
      const res = await fetch('/api/state');
      const data = await res.json();
      state.records = data.records || [];
      els.sumFile.textContent = 'review: ' + (data.reviewFile || '-');
      els.sumTotal.textContent = 'total: ' + (data.total || 0);
      els.sumUnresolved.textContent = 'needs review: ' + (data.unresolved || 0);
      applyFilter();
      if (state.filtered.length > 0) {
        selectByFilteredIndex(0);
      } else {
        renderForm(null);
      }
    }

    function applyFilter() {
      const q = els.search.value.trim().toLowerCase();
      const unresolved = els.onlyUnresolved.checked;
      state.filtered = state.records
        .map((r, i) => ({...r, _idx: i}))
        .filter(r => {
          if (unresolved && !r.needs_review) return false;
          if (!q) return true;
          const bag = [r.title, r.exe, r.dir, r.publisher, r.genre].join(' ').toLowerCase();
          return bag.includes(q);
        });
      renderList();
    }

    function renderList() {
      els.list.innerHTML = '';
      state.filtered.forEach((rec, fi) => {
        const row = document.createElement('div');
        row.className = 'item' + (state.selected === rec._idx ? ' active' : '');
        row.onclick = () => selectByFilteredIndex(fi);
        row.innerHTML =
          '<div class="t">' + escapeHtml(rec.title || '(untitled)') +
          (rec.needs_review ? '<span class="badge">needs review</span>' : '') +
          '</div>' +
          '<div class="d">' + escapeHtml(rec.dir || '-') + '\\\\' + escapeHtml(rec.exe || '-') + '</div>' +
          '<div class="f">' + escapeHtml(rec.genre || 'Other') + ' - ' + escapeHtml(rec.publisher || '') + '</div>';
        els.list.appendChild(row);
      });
    }

    function renderForm(rec) {
      if (!rec) {
        els.form.reset();
        els.dir.value = '';
        els.candidates.value = '';
        return;
      }
      els.dir.value = rec.dir || '';
      els.title.value = rec.title || '';
      els.year.value = rec.year || '';
      els.genre.value = rec.genre || '';
      els.publisher.value = rec.publisher || '';
      els.exe.value = rec.exe || '';
      els.setup.value = rec.setup || '';
      els.note.value = rec.note || '';
      els.candidates.value = (rec.candidates || []).join(', ');
    }

    function selectByFilteredIndex(fi) {
      const rec = state.filtered[fi];
      if (!rec) return;
      state.selected = rec._idx;
      renderList();
      renderForm(state.records[state.selected]);
    }

    function selectedFilteredIndex() {
      return state.filtered.findIndex(x => x._idx === state.selected);
    }

    function moveSelection(delta) {
      if (state.filtered.length === 0) return;
      const current = selectedFilteredIndex();
      const start = current >= 0 ? current : 0;
      let next = start + delta;
      if (next < 0) next = 0;
      if (next >= state.filtered.length) next = state.filtered.length - 1;
      selectByFilteredIndex(next);
    }

    function selectNextUnresolved() {
      if (state.filtered.length === 0) return;
      const current = selectedFilteredIndex();
      const start = current >= 0 ? current + 1 : 0;
      for (let i = start; i < state.filtered.length; i += 1) {
        if (state.filtered[i].needs_review) {
          selectByFilteredIndex(i);
          return;
        }
      }
      for (let i = 0; i < start; i += 1) {
        if (state.filtered[i].needs_review) {
          selectByFilteredIndex(i);
          return;
        }
      }
      setStatus('No unresolved records in current filter');
    }

    function escapeHtml(s) {
      return String(s)
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
    }

    function validateYear(value) {
      const y = String(value || '').trim();
      if (y === '') return null;
      if (!/^\\d{4}$/.test(y)) {
        return 'Year must be 4 digits or blank';
      }
      const n = Number(y);
      if (n < 1980 || n > 2099) {
        return 'Year must be between 1980 and 2099';
      }
      return null;
    }

    async function saveCurrent() {
      if (state.selected < 0) return;
      const yearError = validateYear(els.year.value);
      if (yearError) {
        throw new Error(yearError);
      }
      const payload = {
        title: els.title.value,
        year: els.year.value,
        genre: els.genre.value,
        publisher: els.publisher.value,
        exe: els.exe.value,
        setup: els.setup.value,
        note: els.note.value,
      };
      const res = await fetch('/api/record/' + state.selected, {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'save failed');
      }
      state.records[state.selected] = data.record;
      setStatus('Saved ' + (data.record.title || data.record.dir));
      const keep = state.filtered.findIndex(x => x._idx === state.selected);
      applyFilter();
      if (keep >= 0 && keep < state.filtered.length) {
        selectByFilteredIndex(keep);
      }
      els.sumUnresolved.textContent = 'needs review: ' + state.records.filter(r => r.needs_review).length;
    }

    async function regenerateIndex() {
      const res = await fetch('/api/regenerate', { method: 'POST' });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'regenerate failed');
      }
      setStatus('Regenerated ' + data.output);
    }

    async function applyBulk() {
      const ids = state.filtered.filter(r => r.needs_review).map(r => r._idx);
      if (ids.length === 0) {
        setStatus('No unresolved records in current filter');
        return;
      }

      const year = els.bulkYear.value.trim();
      const yearError = validateYear(year);
      if (yearError) {
        throw new Error('Bulk year: ' + yearError);
      }

      const patch = {};
      if (year !== '') patch.year = year;
      if (els.bulkPublisher.value.trim() !== '') patch.publisher = els.bulkPublisher.value;
      if (els.bulkGenre.value.trim() !== '') patch.genre = els.bulkGenre.value;

      if (Object.keys(patch).length === 0) {
        throw new Error('Provide at least one bulk field');
      }

      const res = await fetch('/api/bulk-update', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ ids, patch }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'bulk update failed');
      }

      await loadState();
      setStatus('Bulk updated ' + data.count + ' record(s)');
    }

    els.search.addEventListener('input', applyFilter);
    els.onlyUnresolved.addEventListener('change', applyFilter);
    els.form.addEventListener('submit', async (ev) => {
      ev.preventDefault();
      try {
        await saveCurrent();
      } catch (err) {
        setStatus(err.message || String(err), true);
      }
    });

    els.regen.addEventListener('click', async () => {
      try {
        await regenerateIndex();
      } catch (err) {
        setStatus(err.message || String(err), true);
      }
    });

    els.bulkApply.addEventListener('click', async () => {
      try {
        await applyBulk();
      } catch (err) {
        setStatus(err.message || String(err), true);
      }
    });

    els.prev.addEventListener('click', () => moveSelection(-1));
    els.next.addEventListener('click', () => moveSelection(1));
    els.nextUnresolved.addEventListener('click', selectNextUnresolved);

    document.addEventListener('keydown', async (ev) => {
      if (ev.ctrlKey && (ev.key === 's' || ev.key === 'S')) {
        ev.preventDefault();
        try {
          await saveCurrent();
        } catch (err) {
          setStatus(err.message || String(err), true);
        }
        return;
      }
      if (ev.key === '[') {
        ev.preventDefault();
        moveSelection(-1);
        return;
      }
      if (ev.key === ']') {
        ev.preventDefault();
        moveSelection(1);
        return;
      }
      if (ev.key === 'n' || ev.key === 'N') {
        ev.preventDefault();
        selectNextUnresolved();
      }
    });

    loadState().catch(err => setStatus(err.message || String(err), true));
  </script>
</body>
</html>
"""


def resolve_review_file(args: argparse.Namespace) -> Path:
    if args.review_file:
        return args.review_file.resolve()
    if not args.launcher_dir:
        raise ValueError("provide either --review-file or --launcher-dir")
    return (args.launcher_dir.resolve() / "SETUP-REVIEW.json")


def main() -> int:
    args = parse_args()

    try:
        review_file = resolve_review_file(args)
        app = MetadataApp(review_file)
    except (ValueError, FileNotFoundError, json.JSONDecodeError) as exc:
        print(f"metadata-ui failed: {exc}")
        return 2

    server = ThreadingHTTPServer((args.host, args.port), make_handler(app))
    url = f"http://{args.host}:{args.port}/"

    print("DGB Metadata UI (Phase 2 MVP)")
    print(f"  review file: {review_file}")
    print(f"  listening:   {url}")
    print("  stop:        Ctrl+C")

    if not args.no_browser:
        try:
            webbrowser.open(url)
        except Exception:
            pass

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
